server:
  port: 6080
#  context-path: /na
spring:
  profiles:
    active: dev
  application:
    name: buyi-admin
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: ENC(aQgkAvb2pbW7sKuepfkeJt00pEdkdZMiDCZil90I6TB0t2Lc0G4hD9Y5iYvA0S3zusSENMFTvqd7Z01xPZDX67g/9UzSi+gJIaJaEu4biip+o2IFxDS3YyE+sPNzl/x1)
    username: ENC(mMW6SXGDHphnqNpFiIHuow==)
    password: ENC(2LxXXydV8DMXbPV1uF1Imw==)
    initialSize: 5
    minIdle: 5
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#    freemarker配置
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .html
    template-loader-path: classpath:/templates/
    settings.template_update_delay: 0
    settings.default_encoding: UTF-8
    settings.classic_compatible: true
    settings.date_format: yyyy-MM-dd
    settings.time_format: HH:mm:ss
    settings.datetime_format: yyyy-MM-dd HH:mm:ss
    order: 1
    request-context-attribute: request
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  # 实体别名扫描
  type-aliases-package: com.puffer.**.entity
  #自定义属性，mybatis扫描持久化层
  mapper-scan-path: com.puffer.admin.mapper

#pageHelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments:  true
  params: count=coutSql
jasypt:
  encryptor:
    password: A#E$#sdf123